### ISSUE TITLE
Implement project saving and loading

### ISSUE THREAD

**Issue by nikmolnar** [VISTAS-IVES/pyvistas#15]
Include data, visualizations, project structure, flythroughs, export configuration. Everything present in CVISTAS.

**Comment by nikmolnar** [comment]
I originally thought we should support loading the older SQLite format, but I'm reconsidering that now... it might be more trouble than it's worth. So maybe instead we just detect when someone tries to load one of those and inform them that it's not supported.

**Comment by TaylorMutch** [comment]
Closed #15.
