### ISSUE TITLE
Camera control icons are clipped

### ISSUE THREAD

**Issue by nikmolnar** [VISTAS-IVES/pyvistas#30]
On Win10, the camera control icons are clipped at the edges:

![screen shot 2017-07-17 at 11 59 28 am](https://user-images.githubusercontent.com/2422416/28284891-7d3889da-6ae7-11e7-859f-dfaa19cc2974.png)

**Comment by TaylorMutch** [comment]
Ah yes I'll hop on this.

**Comment by TaylorMutch** [comment]
Closed #30.
