### ISSUE TITLE
Add requirements-dev.txt

### ISSUE THREAD

**Issue by TaylorMutch** [VISTAS-IVES/pyvistas#55]
Add everything from `requirements.txt`, plus `cx_Freeze` and `pytest`.

**Comment by nikmolnar** [comment]
I don't think we should duplicate items from `requirements.txt`. Devs can install both.

**Comment by nikmolnar** [comment]
There are also few enough dev-only items, I propose not doing this at this time. Install of `cx_Freeze` and `pytest` are only needed for specific actions (not general dev) and can be specified in setup instructions.

**Comment by TaylorMutch** [comment]
Fair enough. When we get to adding dev docs we can specify this.
