### ISSUE TITLE
Camera controls and expand button have display issues on macOS

### ISSUE THREAD

**Issue by nikmolnar** [VISTAS-IVES/pyvistas#67]
1. Icons are not centered on camera controls.  
![not_centered](https://user-images.githubusercontent.com/2422416/29236932-5f829af8-7ec8-11e7-9a9c-e050922ef1a1.png)

2. Camera control "selected" style doesn't clear when another control is selected.  
![two_selected](https://user-images.githubusercontent.com/2422416/29236954-ddd35afa-7ec8-11e7-8fc3-e4b339ee2b70.png)

3. Camera controls and expand button do not immediately move with main window, but will snap into place after the window has stopped moving. This one may not have a suitable solution, as we have to work with the events that are fired by the OS, and the move event just doesn't seem to be sent often enough.

**Comment by TaylorMutch** [comment]
@nikmolnar Yes this behavior is not really idea.

I almost wonder if we could do the UI for these controls a bit better. Right now we have a frame behind each button to get a translucent effect on Windows. However, these buttons are small enough that it almost seems like we don't need the two windows at all. Instead, we could handle the coloring effects with a single button frame that does all the drawing logic (light up on mouse enter, darken on mouse leave if not selected).

**Comment by nikmolnar** [comment]
Maybe. On one hand, that seems at a glance to be more efficient, though that assumes that frames require significant resources. On the other hand, a frame per button makes for nice encapsulation of all the logic for that button.

**Comment by nikmolnar** [comment]
In either event, that doesn't resolve these issues.
