### ISSUE TITLE
Camera controls flicker during redraw on Windows

### ISSUE THREAD

**Issue by nikmolnar** [VISTAS-IVES/pyvistas#69]
It's most noticeable when moving the main window. This doesn't happen to the expand button.

**Comment by TaylorMutch** [comment]
The number of events fired when the main window is moved cascades heavily when there are multiple viewer panels being used. If any rendering is going on in the scene (e.x. vector flow animation), and the main window is moved, the main ui loop slows down considerably.

**Comment by nikmolnar** [comment]
I think that's a separate issue. I'm seeing flicker with an empty project and one viewer panel; I think it's a painting issue.
