### ISSUE TITLE
Add 3D shapefile data plugin

### ISSUE THREAD

**Issue by nikmolnar** [VISTAS-IVES/pyvistas#7]

**Comment by nikmolnar** [comment]
I'm bumping this out of the 1.12 milestone. Though it's technically required for feature parity with C++ VISTAS, it's not being used heavily at the moment and there may be better ways to do this.

**Comment by TaylorMutch** [comment]
Closing since the current shapefile plugin can read in 3D shapefiles. Rendering out 3D terrain from a 2D shapefile can be handled with a combination of sampling elevation data from an `ElevationService` and using that to render out a `VisualizationPlugin3D`.
